// @vitest-environment node
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { bumpVersion, isSemver, setLockVersions } from "./bump-version.mjs";
import {
  VERSION_FILES,
  cargoVersion,
  jsonVersion,
  mismatches,
  readVersions,
  tagVersion,
} from "./read-versions.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const [TAURI, PKG, CARGO] = VERSION_FILES;

const LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "mergeiq-core"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
`;

/** A throwaway tree shaped like the repository, at version 0.1.0. */
function fixture(versions = {}) {
  const root = mkdtempSync(join(tmpdir(), "release-"));
  const write = (file, text) => {
    mkdirSync(dirname(join(root, file)), { recursive: true });
    writeFileSync(join(root, file), text);
  };
  write(
    TAURI,
    `{\n  "productName": "MergeIQ",\n  "version": "${versions.tauri ?? "0.1.0"}",\n  "bundle": { "version": "keep" }\n}\n`,
  );
  write(
    PKG,
    `{\n  "name": "desktop",\n  "version": "${versions.pkg ?? "0.1.0"}",\n  "dependencies": { "x": "1.0.0" }\n}\n`,
  );
  write(
    CARGO,
    `[workspace]\nmembers = ["a"]\n\n[workspace.package]\nversion = "${versions.cargo ?? "0.1.0"}"\nedition = "2021"\n\n[workspace.dependencies]\nserde = "1"\n`,
  );
  write("Cargo.lock", LOCK);
  return root;
}

const snapshot = (root) =>
  Object.fromEntries(
    [...VERSION_FILES, "Cargo.lock"].map((f) => [
      f,
      readFileSync(join(root, f), "utf8"),
    ]),
  );

describe("reading versions", () => {
  it("reads each file's version", () => {
    expect(readVersions(fixture({ cargo: "0.3.0" }))).toEqual({
      [TAURI]: "0.1.0",
      [PKG]: "0.1.0",
      [CARGO]: "0.3.0",
    });
  });

  it("reads the repository's own files", () => {
    const versions = Object.values(readVersions(join(here, "../..")));
    expect(new Set(versions).size).toBe(1);
  });

  it("parses Cargo.toml only under [workspace.package]", () => {
    const text = `[package]\nversion = "9.9.9"\n\n[workspace.package]\nversion = "1.2.3"\n\n[other]\nversion = "7.7.7"\n`;
    expect(cargoVersion(text)).toBe("1.2.3");
    expect(() => cargoVersion(`[package]\nversion = "1.0.0"\n`)).toThrow(
      /workspace\.package/,
    );
  });

  it("rejects JSON without a version", () => {
    expect(() => jsonVersion("{}", "x.json")).toThrow(/x\.json/);
    expect(() => jsonVersion("{", "x.json")).toThrow(/not valid JSON/);
  });

  it("turns tags into versions and rejects non-release tags", () => {
    expect(tagVersion("v0.2.0")).toBe("0.2.0");
    expect(tagVersion("v1.2.3-rc.1")).toBe("1.2.3-rc.1");
    for (const bad of [
      "0.2.0",
      "v0.2",
      "nightly-test",
      "v01.2.3",
      "v1.2.3-",
      "v1.2.3+build",
    ]) {
      expect(tagVersion(bad), bad).toBeNull();
    }
  });
});

describe("mismatch reporting", () => {
  it("is empty when every file matches", () => {
    expect(
      mismatches("0.2.0", {
        [TAURI]: "0.2.0",
        [PKG]: "0.2.0",
        [CARGO]: "0.2.0",
      }),
    ).toEqual([]);
  });

  it("names each mismatching file and the version it contains", () => {
    const lines = mismatches("0.2.0", {
      [TAURI]: "0.1.0",
      [PKG]: "0.2.0",
      [CARGO]: "0.1.5",
    });
    expect(lines).toEqual([
      `${TAURI} contains 0.1.0, expected 0.2.0`,
      `${CARGO} contains 0.1.5, expected 0.2.0`,
    ]);
  });

  it("the CLI gate exits 1 naming tauri.conf.json and its version (Mismatched version)", () => {
    const run = (tag, root) =>
      spawnSync(
        process.execPath,
        [join(here, "read-versions.mjs"), "--tag", tag],
        {
          encoding: "utf8",
          cwd: root,
        },
      );
    // Matching version: the repository's own files agree with their own version.
    const own = readVersions(join(here, "../.."))[TAURI];
    const ok = run(`v${own}`);
    expect(ok.status, ok.stderr).toBe(0);
    const bad = run("v99.0.0");
    expect(bad.status).toBe(1);
    expect(bad.stderr).toContain("tauri.conf.json");
    expect(bad.stderr).toContain(own);
    expect(run("nightly-test").status).toBe(1);
  });
});

describe("bumping", () => {
  it("updates all three files and the workspace lock entries (Bump)", () => {
    const root = fixture();
    const changed = bumpVersion(root, "0.2.0");
    expect(changed).toEqual([TAURI, PKG, CARGO, "Cargo.lock"]);
    expect(readVersions(root)).toEqual({
      [TAURI]: "0.2.0",
      [PKG]: "0.2.0",
      [CARGO]: "0.2.0",
    });
    const files = snapshot(root);
    // Unrelated "version" keys and dependency versions are untouched.
    expect(files[TAURI]).toContain('"version": "keep"');
    expect(files[PKG]).toContain('"x": "1.0.0"');
    expect(files[CARGO]).toContain('serde = "1"');
    expect(files["Cargo.lock"]).toContain(
      'name = "mergeiq-core"\nversion = "0.2.0"',
    );
    expect(files["Cargo.lock"]).toContain('name = "serde"\nversion = "0.1.0"');
  });

  it("accepts pre-release versions", () => {
    const root = fixture();
    bumpVersion(root, "0.1.1-rc.1");
    expect(Object.values(readVersions(root))).toEqual([
      "0.1.1-rc.1",
      "0.1.1-rc.1",
      "0.1.1-rc.1",
    ]);
  });

  it("refuses a version that is not semver and changes no file (Invalid argument)", () => {
    const root = fixture();
    const before = snapshot(root);
    for (const bad of ["0.2", "v0.2.0", "1.2.3.4", "", "latest", "01.2.3"]) {
      expect(() => bumpVersion(root, bad), bad).toThrow(
        /not a valid semantic version/,
      );
    }
    expect(snapshot(root)).toEqual(before);
  });

  it("changes nothing when one file cannot be updated", () => {
    const root = fixture();
    writeFileSync(join(root, PKG), '{ "name": "desktop" }\n');
    const before = snapshot(root);
    expect(() => bumpVersion(root, "0.2.0")).toThrow(PKG);
    expect(snapshot(root)).toEqual(before);
  });

  it("the CLI exits non-zero with a message for an invalid argument", () => {
    const result = spawnSync(
      process.execPath,
      [join(here, "bump-version.mjs"), "0.2"],
      { encoding: "utf8" },
    );
    expect(result.status).toBe(1);
    expect(result.stderr).toMatch(/not a valid semantic version/);
  });

  it("validates semver strictly", () => {
    for (const ok of ["0.0.0", "1.2.3", "1.0.0-alpha.1", "1.0.0-rc.1+build.5"])
      expect(isSemver(ok), ok).toBe(true);
    for (const bad of ["1", "1.2", "1.2.3-", "1.2.3-01", "a.b.c"])
      expect(isSemver(bad), bad).toBe(false);
  });

  it("only moves path crates in Cargo.lock", () => {
    const next = setLockVersions(LOCK, "0.1.0", "0.2.0");
    expect(next).toContain('name = "mergeiq-core"\nversion = "0.2.0"');
    expect(next).toContain('name = "serde"\nversion = "0.1.0"');
  });
});

describe("real repository tree", () => {
  it("bumping a copy of the repository files keeps cargo metadata working", () => {
    const root = mkdtempSync(join(tmpdir(), "release-real-"));
    const repo = join(here, "../..");
    for (const file of [...VERSION_FILES, "Cargo.lock"]) {
      mkdirSync(dirname(join(root, file)), { recursive: true });
      cpSync(join(repo, file), join(root, file));
    }
    const current = readVersions(root)[CARGO];
    const lockBefore = readFileSync(join(root, "Cargo.lock"), "utf8");
    bumpVersion(root, "9.8.7");
    const lockAfter = readFileSync(join(root, "Cargo.lock"), "utf8");
    // Only workspace crates (no `source`) changed; third-party entries at the same version did not.
    expect(lockAfter).not.toBe(lockBefore);
    expect(lockAfter).toContain('name = "mergeiq-core"\nversion = "9.8.7"');
    expect(
      lockAfter.match(
        new RegExp(
          `version = "${current.replace(/\./g, "\\.")}"\\nsource`,
          "g",
        ),
      ) ?? [],
    ).toEqual(
      lockBefore.match(
        new RegExp(
          `version = "${current.replace(/\./g, "\\.")}"\\nsource`,
          "g",
        ),
      ) ?? [],
    );
  });
});
