// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	getSettings: () => __TAURI_INVOKE<SettingsDto>("get_settings"),
	updateSettings: (settings: SettingsDto) => typedError<SettingsDto, IpcError>(__TAURI_INVOKE("update_settings", { settings })),
};

/* Types */
export type AppInfo = {
	name: string,
	version: string,
	platform: string,
};

export type IpcError = { kind: "Settings"; message: string };

/**
 *  Typed IPC view of [`Settings`]; unknown keys in the settings file are preserved on
 *  disk but not exposed over IPC.
 */
export type SettingsDto = {
	theme: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

