// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	getSettings: () => __TAURI_INVOKE<SettingsDto>("get_settings"),
	updateSettings: (settings: SettingsDto) => typedError<SettingsDto, IpcError>(__TAURI_INVOKE("update_settings", { settings })),
	getMergeEditorSettings: () => __TAURI_INVOKE<MergeEditorSettings>("get_merge_editor_settings"),
	updateMergeEditorSettings: (settings: MergeEditorSettings) => typedError<MergeEditorSettings, IpcError>(__TAURI_INVOKE("update_merge_editor_settings", { settings })),
	/**  Opens (or focuses) a repository window. */
	repoOpen: (path: string) => typedError<number, IpcError>(__TAURI_INVOKE("repo_open", { path })),
	repoInfo: (repo: number) => typedError<RepoInfo, IpcError>(__TAURI_INVOKE("repo_info", { repo })),
	recentsList: () => __TAURI_INVOKE<RecentRepoDto[]>("recents_list"),
	recentsRemove: (path: string) => typedError<RecentRepoDto[], IpcError>(__TAURI_INVOKE("recents_remove", { path })),
	repoStatus: (repo: number) => typedError<RepoStatus, IpcError>(__TAURI_INVOKE("repo_status", { repo })),
	conflictLoad: (repo: number, path: PathToken) => typedError<ConflictLoad, IpcError>(__TAURI_INVOKE("conflict_load", { repo, path })),
	/**
	 *  Re-runs the merge analysis for one conflicted file with another whitespace policy
	 *  (the merge editor's whitespace selector).
	 */
	conflictAnalyze: (repo: number, path: PathToken, whitespace: WhitespacePolicy) => typedError<Analysis, IpcError>(__TAURI_INVOKE("conflict_analyze", { repo, path, whitespace })),
	/**  Saves editor text. With `stage` the path is also `git add`ed (resolved). */
	conflictSave: (repo: number, path: PathToken, text: string, encoding: EncodingInfo, stage: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("conflict_save", { repo, path, text, encoding, stage })),
	conflictAcceptSide: (repo: number, path: PathToken, side: AcceptSide) => typedError<null, IpcError>(__TAURI_INVOKE("conflict_accept_side", { repo, path, side })),
	/**  Accepts one side for several files. Every path is tried; failures are reported per path. */
	conflictAcceptMany: (repo: number, paths: PathToken[], side: AcceptSide) => typedError<BatchResult, IpcError>(__TAURI_INVOKE("conflict_accept_many", { repo, paths, side })),
	/**  Resolves a conflict by deleting the file. */
	conflictDelete: (repo: number, path: PathToken) => typedError<null, IpcError>(__TAURI_INVOKE("conflict_delete", { repo, path })),
	conflictRestore: (repo: number, path: PathToken) => typedError<null, IpcError>(__TAURI_INVOKE("conflict_restore", { repo, path })),
	opContinue: (repo: number) => typedError<ControlOutcome, IpcError>(__TAURI_INVOKE("op_continue", { repo })),
	opAbort: (repo: number) => typedError<ControlOutcome, IpcError>(__TAURI_INVOKE("op_abort", { repo })),
	opSkip: (repo: number) => typedError<ControlOutcome, IpcError>(__TAURI_INVOKE("op_skip", { repo })),
	mergeRequestLoad: (id: number) => typedError<MergeRequestDoc, IpcError>(__TAURI_INVOKE("merge_request_load", { id })),
	mergeRequestAnalyze: (id: number, whitespace: WhitespacePolicy) => typedError<Analysis, IpcError>(__TAURI_INVOKE("merge_request_analyze", { id, whitespace })),
	/**
	 *  Writes the result and records the exit code for the waiting CLI process. The window
	 *  stays open; the UI calls [`merge_request_close`] afterwards.
	 */
	mergeRequestSave: (id: number, text: string, encoding: EncodingInfo, mode: SaveMode) => typedError<null, IpcError>(__TAURI_INVOKE("merge_request_save", { id, text, encoding, mode })),
	/**  Closes a request's window; its client gets the recorded exit code (1 if none). */
	requestClose: (id: number) => typedError<null, IpcError>(__TAURI_INVOKE("request_close", { id })),
	cliSetupInfo: () => typedError<CliSetupInfo, IpcError>(__TAURI_INVOKE("cli_setup_info")),
	/**
	 *  Installs the command into `dir` (macOS/Linux: a symlink; Windows: nothing to copy, the
	 *  install folder just needs to be on PATH) and reports whether `dir` is on PATH.
	 */
	cliInstall: (dir: string, admin: boolean) => typedError<InstallOutcome, IpcError>(__TAURI_INVOKE("cli_install", { dir, admin })),
	/**  Windows: adds `dir` to the user PATH. */
	cliAddToPath: (dir: string) => typedError<null, IpcError>(__TAURI_INVOKE("cli_add_to_path", { dir })),
	/**  The `git config --global` commands, as displayed. */
	gitMergetoolCommands: (noBackup: boolean) => __TAURI_INVOKE<string[]>("git_mergetool_commands", { noBackup }),
	/**  Runs the commands. Only invoked after the user confirms in the UI. */
	gitMergetoolConfigure: (noBackup: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("git_mergetool_configure", { noBackup })),
};

/** Events */
export const events = {
	repoChanged: makeEvent<RepoChanged>("repo-changed"),
};

/* Types */
/**  Which side to accept wholesale. */
export type AcceptSide = 
/**  Stage 2. */
"Ours" | 
/**  Stage 3. */
"Theirs";

/**  The full result of a 3-way merge analysis: decoded sides plus classified chunks. */
export type Analysis = {
	/**  The base side. */
	base: SideText,
	/**  The ours side. */
	ours: SideText,
	/**  The theirs side. */
	theirs: SideText,
	/**  Every changed region, in base order. */
	chunks: Chunk[],
	/**
	 *  Encoding/BOM to use when serializing the result (see [`analyze`]'s doc for
	 *  which side this is derived from).
	 */
	encoding: EncodingInfo,
	/**  The result's dominant line terminator, for use on user-typed lines. */
	dominant_eol: Terminator,
};

export type AppInfo = {
	name: string,
	version: string,
	platform: string,
};

/**  One path a batch action could not apply to. */
export type BatchFailure = {
	path: PathToken,
	message: string,
};

/**  Outcome of a multi-file action: what was applied and what failed (the rest still ran). */
export type BatchResult = {
	done: PathToken[],
	failed: BatchFailure[],
};

/**
 *  One changed (or conflicting) region spanning base/ours/theirs, as produced by
 *  [`crate::analyze`].
 */
export type Chunk = {
	/**  Stable index of this chunk within its [`crate::Analysis`]. */
	id: number,
	/**  How this region changed. */
	kind: ChunkKind,
	/**  Range in the base text. */
	base: LineRange,
	/**  Range in the ours text. */
	ours: LineRange,
	/**  Range in the theirs text. */
	theirs: LineRange,
	/**
	 *  Token-level diff of ours/theirs vs base within this chunk. `None` if skipped
	 *  (see `fine_diff_skipped`) or not yet computed.
	 */
	fine: FineDiff | null,
	/**
	 *  Set when this chunk exceeded `Options::fine_diff_max_lines` and fine diffing
	 *  was skipped.
	 */
	fine_diff_skipped: boolean,
	/**  Token-level 3-way merge result, precomputed for `Conflict` chunks only. */
	simple: SimpleResolution | null,
};

/**  How a [`Chunk`]'s region was changed. */
export type ChunkKind = 
/**  Only `ours` changed this region. */
"OursOnly" | 
/**  Only `theirs` changed this region. */
"TheirsOnly" | 
/**  Both sides changed this region identically (under the active whitespace policy). */
"BothSame" | 
/**  Both sides changed this region differently, or touched it at the same point. */
"Conflict";

/**  What the Command line settings page needs to render. */
export type CliSetupInfo = {
	/**  `"macos"`, `"windows"` or `"linux"`. */
	platform: string,
	/**  Folders offered in the picker (on Windows: the install folder only). */
	dirs: InstallDir[],
	/**  Where the `mergeiq` command is already installed, if anywhere we looked. */
	installedAt: string | null,
	/**  git's global config already registers MergeIQ as the merge tool. */
	mergetoolConfigured: boolean,
};

/**  One commit in a side's history. */
export type CommitSummary = {
	/**  Full commit id. */
	sha: string,
	/**  Abbreviated commit id. */
	shortSha: string,
	/**  Subject line. */
	subject: string,
	/**  Author name. */
	author: string,
	/**  Author date, ISO 8601. */
	date: string,
};

/**  A conflicted path. */
export type ConflictEntry = {
	/**  Opaque path token for other calls. */
	path: PathToken,
	/**  Lossy UTF-8 display name. */
	display: string,
	/**  Derived from the stages present. */
	conflictType: ConflictType,
	/**  Present stages in order. */
	stages: StageEntry[],
	/**  Any stage is a symlink (mode 120000). */
	hasSymlink: boolean,
	/**  Any stage is a gitlink / submodule (mode 160000). */
	hasGitlink: boolean,
};

/**  Everything the merge editor needs for one conflicted file. */
export type ConflictLoad = {
	/**  The index entry. */
	entry: ConflictEntry,
	/**  Side labels. */
	labels: SideLabels,
	/**  Commits per side touching the file. */
	context: FileContext,
	/**
	 *  Merge analysis of the stages (an absent stage counts as empty). `None` when the
	 *  content cannot be analysed as text; see `analysis_error`.
	 */
	analysis: Analysis | null,
	/**  Why `analysis` is `None` (binary, undecodable, symlink, submodule). */
	analysisError: string | null,
};

/**  Which index stages are present for a conflicted path. */
export type ConflictType = 
/**  Stages 1, 2, 3. */
"BothModified" | 
/**  Stages 2, 3. */
"BothAdded" | 
/**  Stages 1, 3 (ours deleted it). */
"DeletedByUs" | 
/**  Stages 1, 2 (theirs deleted it). */
"DeletedByThem" | 
/**  Stage 2 only. */
"AddedByUs" | 
/**  Stage 3 only. */
"AddedByThem" | 
/**  Stage 1 only. */
"BothDeleted";

/**  What happened after a control command. */
export type ControlOutcome = {
	/**  The operation is no longer in progress. */
	finished: boolean,
	/**  Combined git output, for display. */
	message: string,
};

/**  A text encoding [`decode`]/[`encode`] can round-trip. */
export type Encoding = 
/**  UTF-8, with or without a BOM. */
"Utf8" | 
/**  UTF-16, little-endian (always BOM-tagged on decode). */
"Utf16Le" | 
/**  UTF-16, big-endian (always BOM-tagged on decode). */
"Utf16Be";

/**
 *  An encoding plus whether a byte-order mark was present, as detected by [`decode`]
 *  and reused by [`encode`] to round-trip byte-exact.
 */
export type EncodingInfo = {
	/**  The detected encoding. */
	encoding: Encoding,
	/**  Whether the input had a byte-order mark. */
	bom: boolean,
};

/**  Commits per side for one path, newest first. */
export type FileContext = {
	/**  Commits on our side since the merge base. */
	ours: CommitSummary[],
	/**  Commits on their side (a single commit for rebase/cherry-pick/revert). */
	theirs: CommitSummary[],
};

/**
 *  Token-level diff of a chunk: ours vs base, and theirs vs base (computed
 *  independently, since the two sides may touch different tokens).
 */
export type FineDiff = {
	/**  Ours vs base. */
	ours: SideFineDiff,
	/**  Theirs vs base. */
	theirs: SideFineDiff,
};

/**  Errors from the git adapter. Serializable so IPC can pass them to the UI. */
export type GitError = 
/**  No usable `git` executable was found. */
{ kind: "GitNotFound" } | 
/**  `git` is older than the minimum supported version. */
{ kind: "GitTooOld"; 
/**  The version string reported by git. */
found: string } | 
/**  The path is inside a bare repository. */
{ kind: "Bare" } | 
/**  The path is not inside a git working tree. */
{ kind: "NotARepo"; 
/**  Display form of the path that was opened. */
path: string } | 
/**  The path has no unmerged index entries. */
{ kind: "NoSuchConflict"; 
/**  Display form of the path. */
path: string } | 
/**  A path token was malformed or points outside the repository. */
{ kind: "InvalidPath" } | 
/**  `continue` was requested while unmerged paths remain. */
{ kind: "UnresolvedPaths"; 
/**  Number of unmerged paths. */
count: number } | 
/**  No merge/rebase/cherry-pick/revert/am is in progress. */
{ kind: "NoOperation" } | 
/**  The requested action does not apply to the current operation. */
{ kind: "Unsupported"; 
/**  What is unsupported. */
what: string } | 
/**  A git command exited unsuccessfully. */
{ kind: "CommandFailed"; 
/**  The git subcommand. */
command: string; 
/**  Captured stderr. */
stderr: string } | 
/**  Filesystem or process error. */
{ kind: "Io"; 
/**  The underlying error text. */
message: string };

/**  A folder the command can be installed into. */
export type InstallDir = {
	path: string,
	/**  Shown in the picker, e.g. `~/.local/bin`. */
	label: string,
	/**  Installing here needs an administrator prompt. */
	needsAdmin: boolean,
};

/**  Result of installing the command. */
export type InstallOutcome = {
	linkPath: string,
	onPath: boolean,
	pathHint: PathHint | null,
};

export type IpcError = { kind: "Settings"; message: string } | { kind: "Git"; message: GitError } | { kind: "NoRepo" } | { kind: "Request"; message: string };

/**
 *  A line's content range `[start, end)` (byte offsets, terminator excluded) plus its
 *  original terminator.
 */
export type Line = {
	/**  Byte offset of the line's first content byte. */
	start: number,
	/**  Byte offset just past the line's last content byte (terminator excluded). */
	end: number,
	/**  This line's original terminator. */
	term: Terminator,
};

/**
 *  A half-open `[start, end)` line-index range. An empty range (`start == end`)
 *  represents an insertion point.
 */
export type LineRange = {
	/**  Line index of the range's start. */
	start: number,
	/**  Line index just past the range's end. */
	end: number,
};

/**
 *  Merge editor preferences (`merge-editor-ui`), stored under `mergeEditor` in the
 *  settings file and exposed over IPC as-is (every field has a default).
 */
export type MergeEditorSettings = {
	/**  Apply non-conflicting chunks automatically when a file opens. */
	autoApplyNonConflicting?: boolean,
	/**  Show the read-only base pane. */
	showBase?: boolean,
	/**  Fold long unchanged regions. */
	collapseUnchanged?: boolean,
	/**  Keep the panes scroll-aligned. */
	syncScroll?: boolean,
	/**  Whitespace policy used when analysing a file. */
	whitespacePolicy?: WhitespacePolicy,
	/**  In a repository window, open the next unresolved file after a resolved save. */
	autoAdvanceAfterSave?: boolean,
};

/**  Left/right labels for the editor headers. */
export type MergeLabels = {
	/**  Left pane (ours / local). */
	left: SideLabel,
	/**  Right pane (theirs / remote). */
	right: SideLabel,
};

/**  Everything the merge window needs (the UI's `MergeDocument`, minus the path token). */
export type MergeRequestDoc = {
	/**  Path shown in the title bar. */
	displayPath: string,
	/**  Engine analysis of the three sides. */
	analysis: Analysis,
	/**  Header labels. */
	labels: MergeLabels,
	/**  Commits touching the file per side, when in a repository. */
	context: FileContext | null,
};

/**  The operation that produced (or may produce) conflicts. */
export type Operation = 
/**  Nothing in progress. */
{ kind: "None" } | 
/**  `git merge`. */
{ kind: "Merge" } | 
/**  `git rebase` (merge or apply backend). */
{ kind: "Rebase"; 
/**  1-based step currently stopped at. */
step: number; 
/**  Total steps. */
total: number; 
/**  Commit being rebased onto. */
onto: string } | 
/**  `git cherry-pick`. */
{ kind: "CherryPick" } | 
/**  `git revert`. */
{ kind: "Revert" } | 
/**  `git am`. */
{ kind: "Am" } | 
/**  Conflicts exist but no state file explains them (e.g. `git stash pop`). */
{ kind: "Unknown" };

/**  A line to add to a shell start-up file when the folder is not on PATH. */
export type PathHint = {
	rcFile: string,
	line: string,
};

/**  Opaque, URL-safe base64 of a [`RepoPath`]'s bytes. Pass back to the adapter unchanged. */
export type PathToken = string;

/**  A remembered repository, as the home view lists it. */
export type RecentRepoDto = {
	name: string,
	path: string,
	openedAt: number,
	/**  `false` when the folder no longer exists. */
	exists: boolean,
};

/**  Emitted (as `repo-changed`) to a repository's window when its index or operation state changes. */
export type RepoChanged = null;

/**  The repository a window was opened for. */
export type RepoInfo = {
	name: string,
	path: string,
};

/**  Snapshot of a repository's conflict state. */
export type RepoStatus = {
	/**  Worktree root (lossy display form). */
	root: string,
	/**  Checked-out branch, or `None` when HEAD is detached (e.g. mid-rebase). */
	branch: string | null,
	/**  Operation in progress. */
	operation: Operation,
	/**  Side labels for that operation. */
	labels: SideLabels,
	/**  Unmerged paths. */
	conflicts: ConflictEntry[],
};

/**  How the editor's Apply was chosen (mirrors the UI's `SaveMode`). */
export type SaveMode = 
/**  Everything resolved. */
"resolved" | 
/**  Unresolved conflicts written as markers. */
"markers" | 
/**  "Mark as resolved anyway". */
"force";

/**
 *  Typed IPC view of [`Settings`]; unknown keys in the settings file are preserved on
 *  disk but not exposed over IPC.
 */
export type SettingsDto = {
	theme: string,
};

/**  Token-level diff of one side's text vs base text (both chunk-relative). */
export type SideFineDiff = {
	/**  Ranges within the base text that differ from this side. */
	base_ranges: Utf16Range[],
	/**  Ranges within this side's text that differ from base. */
	side_ranges: Utf16Range[],
};

/**  What one side of the conflict means to the user. */
export type SideLabel = {
	/**  Human role, e.g. `"Your branch"`. */
	role: string,
	/**  Branch/ref name, if known. */
	refName: string | null,
	/**  Abbreviated commit id. */
	shortSha: string | null,
	/**  Commit subject. */
	subject: string | null,
	/**  Commit author name. */
	author: string | null,
	/**  Raw git term (`"ours"`/`"theirs"`), secondary info only. */
	gitTerm: string,
};

/**  Labels for stage 2 (`ours`) and stage 3 (`theirs`). */
export type SideLabels = {
	/**  Stage 2. */
	ours: SideLabel,
	/**  Stage 3. */
	theirs: SideLabel,
};

/**  One side's decoded text and line table. */
export type SideText = {
	/**  The decoded text. */
	text: string,
	/**  `text`'s line table. */
	lines: Line[],
};

/**  Result of a token-level 3-way merge attempt for one conflict chunk. */
export type SimpleResolution = 
/**
 *  Token-level edits from both sides didn't overlap or touch; this is the
 *  merged text.
 */
{ Resolved: string } | 
/**  Token-level edits overlapped or touched; needs a human. */
"Unresolvable";

/**  One index stage of a conflicted path. */
export type StageEntry = {
	/**  1 = base, 2 = ours, 3 = theirs. */
	stage: number,
	/**  Octal file mode, e.g. `"100644"`. */
	mode: string,
	/**  Blob (or gitlink commit) id. */
	oid: string,
};

/**  A line's original terminator, preserved for byte-exact round-tripping. */
export type Terminator = 
/**  `\n`. */
"Lf" | 
/**  `\r\n`. */
"Crlf" | 
/**  A lone `\r`. */
"Cr" | 
/**  The final line of a file with no trailing terminator. */
"None";

/**  A UTF-16 code-unit range `[start, end)`, matching JavaScript string indexing. */
export type Utf16Range = {
	/**  UTF-16 code unit offset of the range's start. */
	start: number,
	/**  UTF-16 code unit offset just past the range's end. */
	end: number,
};

/**  How line content is normalized for equality when diffing. */
export type WhitespacePolicy = 
/**  Lines must match byte-for-byte. */
"Exact" | 
/**  Trailing whitespace is ignored. */
"TrimTrailing" | 
/**
 *  Leading/trailing whitespace is ignored and interior whitespace runs collapse
 *  to a single space.
 */
"IgnoreAmount" | 
/**  All whitespace is ignored. */
"IgnoreAll";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

