[package]
name = "mergeiq-git"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
dunce.workspace = true
mergeiq-core = { path = "../mergeiq-core" }
specta = { version = "2.0.0-rc.25", optional = true, features = ["derive"] }
base64 = "0.22"
notify = "8"
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
which = "8"
shell-words = "1.1.1"

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.27.0"

[features]
specta = ["dep:specta", "mergeiq-core/specta"]
